# Generated by Django 3.2.7 on 2021-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.FileField(default='uploads/users/default.jpg', upload_to='uploads/users/firgerprints/'),
        ),
    ]
