# Generated by Django 3.2.7 on 2021-10-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_subjects_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='image',
        ),
    ]
