# Generated by Django 3.2.7 on 2021-10-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20211003_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='None', max_length=100)),
                ('_from', models.DateTimeField()),
                ('_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Graduated', 'Graduated'), ('Current', 'Current'), ('Dropped_out', 'Dropped out')], default='Graduated', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Academic history',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('region_or_provinve', models.CharField(default='Nairobi', max_length=100)),
                ('state_or_county', models.CharField(default='Nairobi', max_length=100)),
                ('sub_county', models.CharField(default='Madhare North', max_length=100)),
                ('location', models.CharField(default='Uthiru', max_length=100)),
                ('sub_location', models.CharField(default='kilimani', max_length=100)),
                ('village', models.CharField(default='machau', max_length=100)),
                ('zip_code', models.CharField(default='41200', max_length=100)),
                ('postal_address', models.CharField(default='P.O BOX 45-41200 Nairobi-Kenya', max_length=100)),
                ('street', models.CharField(default='Mfangano', max_length=100)),
                ('apartment', models.CharField(default="Jek's Chambers", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('_from', models.DateTimeField()),
                ('_to', models.DateTimeField(blank=True, help_text='leave blank if current', null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Transfered', 'Transfered')], default='Graduated', max_length=50)),
                ('insurance_name', models.CharField(default='NHIF', max_length=100)),
                ('insurance_id', models.CharField(default='12355', max_length=100)),
                ('bank_name', models.CharField(default='National Bank', max_length=100)),
                ('bank_account_number', models.CharField(default='1260777345621', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Work history',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Petty crime', max_length=100)),
                ('location', models.CharField(default='Nairobi', max_length=100)),
                ('time', models.DateTimeField()),
                ('description', models.CharField(default='Description here', max_length=100)),
                ('scene_image', models.FileField(upload_to='uploads/users/firgerprints/')),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open'), ('Solved', 'Solved'), ('Secret', 'Secret')], default='Closed', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='management.subjects')),
            ],
            options={
                'verbose_name_plural': 'Crime Records',
            },
        ),
        migrations.AddField(
            model_name='subjects',
            name='academic_history',
            field=models.ManyToManyField(default='None', to='management.Academic_history'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='crime_history',
            field=models.ManyToManyField(default='None', to='management.Crime'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='residence',
            field=models.ManyToManyField(default='None', to='management.Residence'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='work_history',
            field=models.ManyToManyField(default='None', to='management.Work_history'),
        ),
    ]
