# Generated by Django 3.2.7 on 2021-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20211003_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
