# Generated by Django 3.2.7 on 2021-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_crime_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_history',
            name='bank_account_number',
            field=models.CharField(default='1260777345621', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='work_history',
            name='insurance_id',
            field=models.CharField(default='12355', max_length=100, unique=True),
        ),
    ]
