# Generated by Django 3.2.7 on 2021-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20211003_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='crime_history',
            field=models.ManyToManyField(blank=True, default='None', null=True, to='management.Crime'),
        ),
    ]
