# Generated by Django 3.2.7 on 2021-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_subjects_crime_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.FileField(default='uploads/users/default.jpg', upload_to='uploads/users/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Head of department officer'), (2, 'County security officer'), (3, 'Regional security officer'), (4, 'Minister of security'), (5, 'admin')], primary_key=True, serialize=False),
        ),
    ]
