# Generated by Django 3.2.7 on 2021-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20211003_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='description',
            field=models.TextField(default='Description here', max_length=255),
        ),
    ]
